application: sayitaintsoowoahwoah
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.app
  secure: always

libraries:
- name: jinja2
  version: latest